import { ListingItem, SellerProfile } from '../src/types';

export const initialSellers: SellerProfile[] = [
  {
    id: 'seller-1',
    name: 'Sarah Mwangi',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    phone: '+254 722 458 912',
    email: 'sarah.mwangi@invictus.co',
    memberSince: 'March 2024',
    rating: 4.95,
    reviewCount: 48,
    isIdVerified: true,
    isTopRated: true,
    fastShipper: true,
    location: 'Westlands, Nairobi',
    city: 'Nairobi',
    country: 'Kenya',
    salesCompleted: 62,
    reviews: [
      {
        id: 'rev-1',
        reviewerName: 'Brian Kip',
        reviewerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
        rating: 5,
        comment: 'Super fast handover at Sarit Centre safe zone! Item exactly as listed.',
        createdAt: '2 days ago',
        verifiedPurchase: true,
      },
      {
        id: 'rev-2',
        reviewerName: 'Amina O.',
        reviewerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=120&q=80',
        rating: 5,
        comment: 'Paid with M-Pesa via Invictus Escrow. Received the phone in pristine condition.',
        createdAt: '1 week ago',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'seller-2',
    name: 'David Chen',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    phone: '+1 415 889 2301',
    email: 'david.chen@gmail.com',
    memberSince: 'January 2023',
    rating: 4.88,
    reviewCount: 114,
    isIdVerified: true,
    isTopRated: true,
    fastShipper: true,
    location: 'SoHo, New York',
    city: 'New York',
    country: 'USA',
    salesCompleted: 140,
    reviews: [
      {
        id: 'rev-3',
        reviewerName: 'Marcus V.',
        reviewerAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=120&q=80',
        rating: 5,
        comment: 'Camera arrived double boxed with tracking. Escrow released smoothly.',
        createdAt: '3 days ago',
        verifiedPurchase: true,
      },
    ],
  },
  {
    id: 'seller-3',
    name: 'Kipchoge Wekesa',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    phone: '+254 711 902 344',
    email: 'kip.wekesa@techhub.ke',
    memberSince: 'November 2024',
    rating: 4.9,
    reviewCount: 29,
    isIdVerified: true,
    isTopRated: false,
    fastShipper: true,
    location: 'Kilimani, Nairobi',
    city: 'Nairobi',
    country: 'Kenya',
    salesCompleted: 34,
    reviews: [],
  },
  {
    id: 'seller-4',
    name: 'Elena Rostova',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    phone: '+44 7700 900123',
    email: 'elena.vintage@londonresale.co.uk',
    memberSince: 'June 2023',
    rating: 4.97,
    reviewCount: 82,
    isIdVerified: true,
    isTopRated: true,
    fastShipper: true,
    location: 'Kensington, London',
    city: 'London',
    country: 'United Kingdom',
    salesCompleted: 95,
    reviews: [],
  },
];

export const initialListings: ListingItem[] = [
  {
    id: 'item-101',
    title: 'Apple iPhone 15 Pro Max 256GB - Natural Titanium (Unlocked)',
    description: 'Selling pristine condition iPhone 15 Pro Max in Natural Titanium. Battery health 98%. Includes original braided USB-C cable and genuine Apple silicone case. 100% genuine, iCloud unlocked and ready for new owner.',
    priceUSD: 880,
    priceKES: 114400,
    originalRetailUSD: 1199,
    category: 'Phones & Tablets',
    subcategory: 'Smartphones',
    condition: 'Like New',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1695048065063-4709403d15b0?auto=format&fit=crop&w=900&q=80',
    ],
    seller: initialSellers[0],
    deliveryMethod: 'both',
    shippingFeeUSD: 15,
    shippingFeeKES: 1950,
    pickupLocation: {
      name: 'Sarit Centre Mall / Westgate Entrance',
      safeSpotDescription: 'Inside Java House cafe or 24/7 guarded security desk.',
      address: 'Karuna Rd, Westlands, Nairobi',
      distanceMiles: 1.4,
    },
    viewsCount: 342,
    likesCount: 54,
    createdAt: '2 hours ago',
    status: 'active',
    escrowStatus: 'NONE',
    aiAppraisal: {
      confidence: 0.96,
      suggestedPriceRangeUSD: { min: 820, avg: 890, max: 940 },
      suggestedPriceRangeKES: { min: 106600, avg: 115700, max: 122200 },
      detectedBrand: 'Apple',
      sellingTip: 'High buyer demand for Natural Titanium colorway. Offering local pickup in Westlands will sell 40% faster.',
      tags: ['iPhone 15 Pro Max', 'Apple', 'Unlocked', 'Titanium', '256GB'],
    },
  },
  {
    id: 'item-102',
    title: 'Sony PlayStation 5 Disc Edition + DualSense Controller & 2 Games',
    description: 'Barely used PS5 Disc Console with original box, all cables, HDMI 2.1, vertical stand, and Spider-Man 2 + FC 24 physical discs. Super quiet, adult owned in pet-free home.',
    priceUSD: 420,
    priceKES: 54600,
    originalRetailUSD: 499,
    category: 'Gaming & Consoles',
    subcategory: 'Home Consoles',
    condition: 'Like New',
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=900&q=80',
    ],
    seller: initialSellers[2],
    deliveryMethod: 'both',
    shippingFeeUSD: 20,
    shippingFeeKES: 2600,
    pickupLocation: {
      name: 'Yaya Centre Safe Zone',
      safeSpotDescription: 'Artcaffe ground floor terrace (public verified meetup point).',
      address: 'Argwings Kodhek Rd, Kilimani, Nairobi',
      distanceMiles: 2.8,
    },
    viewsCount: 512,
    likesCount: 88,
    createdAt: '5 hours ago',
    status: 'reserved',
    escrowStatus: 'HELD_IN_ESCROW',
    escrowHoldDetails: {
      transactionId: 'tx-escrow-ps5-102',
      paymentMethod: 'mpesa',
      paidAmountUSD: 420,
      paidAmountKES: 54600,
      commissionFeeUSD: 13,
      commissionFeeKES: 1690,
      heldAt: 'Today, 9:15 AM',
      buyerId: 'user-buyer-1',
      buyerName: 'Alex Kiprono',
      buyerPhone: '+254712345678',
      mpesaReceipt: 'QKA781299Z',
    },
    aiAppraisal: {
      confidence: 0.94,
      suggestedPriceRangeUSD: { min: 390, avg: 430, max: 470 },
      suggestedPriceRangeKES: { min: 50700, avg: 55900, max: 61100 },
      detectedBrand: 'Sony Interactive Entertainment',
      sellingTip: 'Bundling Spider-Man 2 increases buyer conversion rate by 2.3x.',
      tags: ['PS5', 'PlayStation 5', 'Sony', 'Gaming', 'DualSense'],
    },
  },
  {
    id: 'item-103',
    title: 'Nike Air Jordan 1 Retro High OG "Chicago Lost & Found" (Size 10.5 US)',
    description: 'Deadstock brand new in box with original receipt from SNKRS app. Proof of authenticity verified. Comes with pre-aged box, newspaper wrapping paper, and extra white/black laces.',
    priceUSD: 360,
    priceKES: 46800,
    originalRetailUSD: 180,
    category: 'Sneakers & Shoes',
    subcategory: 'Collectible Sneakers',
    condition: 'Brand New',
    images: [
      'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=900&q=80',
    ],
    seller: initialSellers[1],
    deliveryMethod: 'shipping',
    shippingFeeUSD: 18,
    shippingFeeKES: 2340,
    viewsCount: 890,
    likesCount: 142,
    createdAt: '1 day ago',
    status: 'active',
    escrowStatus: 'NONE',
    aiAppraisal: {
      confidence: 0.98,
      suggestedPriceRangeUSD: { min: 340, avg: 375, max: 410 },
      suggestedPriceRangeKES: { min: 44200, avg: 48750, max: 53300 },
      detectedBrand: 'Nike / Jordan',
      sellingTip: 'Sneakers authenticated with Escrow buyer protection generate 85% higher trust.',
      tags: ['Air Jordan 1', 'Chicago', 'Lost & Found', 'Deadstock', 'Sneakers'],
    },
  },
  {
    id: 'item-104',
    title: 'Sony Alpha A7 IV Mirrorless Camera Body (Low Shutter Count: 4,120)',
    description: '33MP full-frame sensor, 4K 60p, 10-bit color, advanced autofocus. Meticulously cared for, screen protector installed since day one. Includes 2 original NP-FZ100 batteries, dual charger, neck strap and box.',
    priceUSD: 1750,
    priceKES: 227500,
    originalRetailUSD: 2499,
    category: 'Cameras & Photo',
    subcategory: 'Mirrorless Cameras',
    condition: 'Like New',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=900&q=80',
    ],
    seller: initialSellers[1],
    deliveryMethod: 'both',
    shippingFeeUSD: 25,
    shippingFeeKES: 3250,
    pickupLocation: {
      name: 'Union Square Manhattan Meetup Spot',
      safeSpotDescription: 'Police precinct lobby or Apple Store 5th Ave courtyard.',
      address: 'Union Square, Manhattan, NY',
      distanceMiles: 4.2,
    },
    viewsCount: 620,
    likesCount: 77,
    createdAt: '1 day ago',
    status: 'active',
    escrowStatus: 'NONE',
    aiAppraisal: {
      confidence: 0.95,
      suggestedPriceRangeUSD: { min: 1650, avg: 1780, max: 1890 },
      suggestedPriceRangeKES: { min: 214500, avg: 231400, max: 245700 },
      detectedBrand: 'Sony Alpha',
      sellingTip: 'Mentioning the exact shutter count (4,120) boosts buyer confidence significantly.',
      tags: ['Sony A7IV', 'Full Frame', 'Mirrorless', '4K60', 'Photography'],
    },
  },
  {
    id: 'item-105',
    title: 'Apple MacBook Pro 14" M3 Pro Chip (18GB RAM, 512GB SSD, Space Black)',
    description: 'Space Black MacBook Pro 14-inch with M3 Pro. Stunning Liquid Retina XDR 120Hz display, MagSafe 3 charger, 100% battery capacity (only 19 cycles). AppleCare+ active until December 2026.',
    priceUSD: 1490,
    priceKES: 193700,
    originalRetailUSD: 1999,
    category: 'Electronics',
    subcategory: 'Laptops',
    condition: 'Like New',
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=900&q=80',
    ],
    seller: initialSellers[0],
    deliveryMethod: 'both',
    shippingFeeUSD: 22,
    shippingFeeKES: 2860,
    pickupLocation: {
      name: 'The Hub Karen Safe Meetup',
      safeSpotDescription: 'Central amphitheatre plaza in front of security office.',
      address: 'Dagoretti Rd, Karen, Nairobi',
      distanceMiles: 8.5,
    },
    viewsCount: 780,
    likesCount: 110,
    createdAt: '3 days ago',
    status: 'active',
    escrowStatus: 'NONE',
    aiAppraisal: {
      confidence: 0.97,
      suggestedPriceRangeUSD: { min: 1420, avg: 1510, max: 1600 },
      suggestedPriceRangeKES: { min: 184600, avg: 196300, max: 208000 },
      detectedBrand: 'Apple',
      sellingTip: 'Active AppleCare+ warranty transfer gives buyers maximum peace of mind.',
      tags: ['MacBook Pro', 'M3 Pro', 'Apple Silicon', 'Space Black', 'Laptop'],
    },
  },
  {
    id: 'item-106',
    title: 'Vintage Schott NYC Leather Motorcycle Biker Jacket (Black, Size L)',
    description: 'Authentic Made in USA Schott Perfecto style heavyweight steerhide leather jacket. Beautiful natural patina on edges, heavy duty Talon zippers, quilted warm interior lining. Timeless piece.',
    priceUSD: 395,
    priceKES: 51350,
    originalRetailUSD: 950,
    category: 'Fashion & Apparel',
    subcategory: 'Jackets & Coats',
    condition: 'Good',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=900&q=80',
    ],
    seller: initialSellers[3],
    deliveryMethod: 'shipping',
    shippingFeeUSD: 20,
    shippingFeeKES: 2600,
    viewsCount: 410,
    likesCount: 63,
    createdAt: '4 days ago',
    status: 'active',
    escrowStatus: 'NONE',
    aiAppraisal: {
      confidence: 0.92,
      suggestedPriceRangeUSD: { min: 350, avg: 410, max: 480 },
      suggestedPriceRangeKES: { min: 45500, avg: 53300, max: 62400 },
      detectedBrand: 'Schott NYC',
      sellingTip: 'Authentic vintage leather appreciates well. Include sleeve and pit-to-pit measurements in chat.',
      tags: ['Schott NYC', 'Leather Jacket', 'Vintage', 'Biker', 'Made in USA'],
    },
  },
];
